### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by maxslug** [PeWu/topola-viewer#12]
Sorry, I don't know NPM very well, but running into this when trying to bootstrap a copy of topoloa-viewer on my server.   This is on an Ubuntu 18.04 LTS system.   `apt_get install npm`  and then a git clone from today.     Here is the error I'm seeing : 

```
43274 verbose addNameRange registry:https://registry.npmjs.org/@types%2fparse-json not in flight; fetching
43275 verbose stack Error: Missing required argument #1
43275 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
43275 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
43275 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
43275 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
43275 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
43275 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
43275 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
43275 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
43275 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
43275 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
43276 verbose cwd /home/warped/src/topola-viewer
43277 error Linux 4.15.0-88-generic
43278 error argv "/usr/bin/node" "/usr/bin/npm" "install"
43279 error node v8.10.0
43280 error npm  v3.5.2
43281 error code EMISSINGARG
43282 error typeerror Error: Missing required argument #1
43282 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
43282 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
43282 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
43282 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
43282 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
43282 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
43282 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
43282 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
43282 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
43282 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
43283 error typeerror This is an error with npm itself. Please report this error at:
43283 error typeerror     <http://github.com/npm/npm/issues>
43284 verbose exit [ 1, true ]
```

Any ideas?
Thanks,
-m

**Comment by maxslug** [comment]
also likely unrelated are these warnings...
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface ha
```

**Comment by PeWu** [comment]
Looks like a known problem. Have a look at the following links, maybe there is a solution:
- https://npm.community/t/npm-install-error-missing-required-argument-1/8113
- https://github.com/npm/cli/issues/681

**Comment by maxslug** [comment]
Thanks @PeWu !  Looks like the NPM that ships with Ubuntu 18.04 LTS is too old, so I have to see about upgrading that.
